users/models.py
from manage import db
from werkzeug.security import generate_password_hash, check_password_hash

from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(40), nullable=False)
    email = db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String, nullable=False)

    def __repr__(self):
        return f'<User {self.name}>'

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def save(self):
        db.session.add(self)
        db.session.commit()

users/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email


class RegistrationForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    email = EmailField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])
    password_confirmation = PasswordField('password confirmation', validators=[DataRequired()])

    def validate(self):
        check_validate = super(RegistrationForm, self).validate()
        # if our validators do not pass
        if not check_validate:
            return False

        if self.password.data != self.password_confirmation.data:
            self.password.errors.append('passwords dont match')
            self.password_confirmation.errors.append('passwords dont match')
            return False
        return True




class LoginForm(FlaskForm):
    email = EmailField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])

app.py
from manage import create_app, db, migrate, login_manager
from config import DevConfig

from users.models import User


app = create_app(DevConfig)

@login_manager.user_loader
def load_user(id):
    return User.query.get(id)


@app.shell_context_processor
def create_shell_context():
    return  dict(app=app, db=db, migrate=migrate, User=User)


if __name__ == '__main__':
    app.run()

users/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user

from .forms import LoginForm, RegistrationForm
from .models import User

users_app = Blueprint('users_app', __name__)


@users_app.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    if request.method == 'POST':
        if login_form.validate_on_submit():
            user = User.query.filter_by(email=login_form.email.data).first()
            if user:
                if user.check_password(login_form.password.data):
                    login_user(user)
                    return redirect(url_for('users_app.profile', id=user.id))
            else:
                flash('wrong user name or password please try again', 'danger')
                # return redirect(url_for('users_app.login'))


    return render_template('users/login.html', login_form=login_form)


@users_app.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegistrationForm()
    if request.method == 'POST':
        if register_form.validate_on_submit():
            user = User()
            register_form.populate_obj(user)
            user.set_password(register_form.password.data)
            user.save()
            flash('account created successfully you can login now', 'success')
            return redirect(url_for('users_app.login'))


    return render_template('users/register.html', register_form=register_form)




@users_app.route('/login_success')
@login_required
def login_success():
    return render_template('users/login_success.html')


@users_app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users_app.login'))


@users_app.route('/profile/<int:id>')
def profile(id):
    user = User.query.get_or_404(id)
    return render_template('users/profile.html', user=user)

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title> Assignment | {% block title %} {% endblock %} </title>

        <!-- include bootstrap framework css -->
        <!-- <link href="static/bulma/css/bulma.min.css" rel="stylesheet"> -->

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


        {% block styles %} {% endblock %}
    </head>
    <body>

        {% include 'header.html' %}

        <div class="container">
            {% include 'messages.html' %}
            {% block content %}

            {% endblock %}
        </div>



        <!-- include bootstrap javascript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


        {% block scripts %}

        {% endblock %}


    </body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">


    <div class="container">
      <a class="navbar-brand" href="#"> Assignment </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>

          <ul class="navbar-nav ml-auto">

              {% if current_user.is_authenticated %}

                <div class="dropdown">
                  <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ current_user.name }}
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for('users_app.logout') }}">Logout</a>
                  </div>
                </div>

              {% else %}

                <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{{ url_for('users_app.login') }}"> login </a>
                </li>

              {% endif %}



          </ul>

      </div>
    </div>
</nav>

templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}

    {% if messages %}

        {% for category, msg in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
              <strong> Message: </strong> {{ msg }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endfor %}

    {% endif %}


{% endwith %}

templates/users/login.html
{% extends 'base.html' %}


{% block title %} Login {% endblock %}

{% block content %}

    <div class="row">

        <div class="col offset-md-3 col-md-6">
            <div class="media">
                <div class="media-body">
                    <form method="post">

                        {{ login_form.csrf_token() }}

                        <div class="form-group">
                            {{ login_form.email.label }}
                            {{ login_form.email(class='form-control') }}
                            {% for error in login_form.email.errors %}
                                <div class="text-danger">
                                    <strong> {{ error }} </strong>
                                </div>
                            {% endfor %}
                        </div>


                         <div class="form-group">
                            {{ login_form.password.label }}
                            {{ login_form.password(class='form-control') }}
                            {% for error in login_form.password.errors %}
                                <div class="text-danger">
                                    <strong> {{ error }} </strong>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary"> login </button>
                            Dont have account?
                            <a href="{{ url_for('users_app.register') }}"> register here </a>
                        </div>




                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/login_success.html
{% extends 'base.html' %}


{% block title %} Success {% endblock %}

{% block content %}

    <p>
        logged in successfully you can now go to your
        <a href=""> account </a>
    </p>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}


{% block title %} Login {% endblock %}

{% block content %}

  <div class="row">
      <div class="col col-md-3">
          <img src="static/images/stevie.jpg">
      </div>
      <div class="col">
        <h4> {{ user.name }}'s profile </h4>
      </div>
  </div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}


{% block title %} regitser {% endblock %}

{% block content %}


    <div class="row">

        <div class="col offset-md-3 col-md-6">
            <div class="media">
                <div class="media-body">
                    <form method="post">

                        {{ register_form.csrf_token() }}

                        <div class="form-group">
                            {{ register_form.name.label }}
                            {{ register_form.name(class='form-control') }}
                            {% for error in register_form.name.errors %}
                                <div class="text-danger">
                                    <strong> {{ error }} </strong>
                                </div>
                            {% endfor %}
                        </div>


                         <div class="form-group">
                            {{ register_form.email.label }}
                            {{ register_form.email(class='form-control') }}
                            {% for error in register_form.email.errors %}
                                <div class="text-danger">
                                    <strong> {{ error }} </strong>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="form-group">
                            {{ register_form.password.label }}
                            {{ register_form.password(class='form-control') }}
                            {% for error in register_form.password.errors %}
                                <div class="text-danger">
                                    <strong> {{ error }} </strong>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="form-group">
                            {{ register_form.password_confirmation.label }}
                            {{ register_form.password_confirmation(class='form-control') }}
                            {% for error in register_form.password_confirmation.errors %}
                                <div class="text-danger">
                                    <strong> {{ error }} </strong>
                                </div>
                            {% endfor %}
                        </div>



                        <div class="form-group">
                            <button class="btn btn-primary"> register </button>
                        </div>




                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}